print(15+15)
resultado=10/3
print(resultado)
print(type(resultado))
print(8+15)
print(100-37)
print(6*7)
print(50/4)
print(50//4)
print(29/5)
print(5**5)
print(3.5*4)
print(12.5*4)
Total=7/2
print(Total)
print(type(Total))
print(15*2)
print(3*9)
print(12**2)
print((8+6+10)/3)
print((10+5)*2)
print(10+(5*2))
print(100%9)
print((7*3)+5)
print((200-20)/10)
nome=input("qual é o seu nome?\n")
print("olá", nome)
idade=input("qual é a sua idade?\n")
print("você tem", idade, "anos")
n1=int(input("digite um numero\n"))
n2=int(input("digite mais um numero\n"))
print(n1+n2)
n3=float(input("digite um numero decimal\n"))
n4=float(input("digite mais um numero decimal\n"))
print(n3*n4)
n5=float(input("digite um numero\n"))
print(n5*2)
n6=float(input("digite um numero\n"))
n7=float(input("digite mais um numero\n"))
print(n6//n7)
ano=int(input("digite seu ano de nascimento\n"))
print(2025-ano)
n8=float(input("digite um numero\n"))
n9=float(input("digite um numero\n"))
n10=float(input("digite um numero\n"))
print((n8+n9+n10)/3)